---
title: "introduction"
description: 'Label designer for multiple porpouses'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE, eval=FALSE}
source("https://raw.githubusercontent.com/Flavjack/inti/master/pkgdown/favicon/docs.r")
```

# Labels for a experimental design

## Example label

The experimental design fieldbook were deployed in "Tarpuy" <https://inkaverse.com/articles/apps.html>

```{r, echo=TRUE, eval=FALSE}
library(huito)
library(gsheet)

url <- paste0("https://docs.google.com/spreadsheets/d/"
       , "1q0EZmZBt52ca-0VbididjJy2jXTwf06laJpzvkQJWvc/edit#gid=107939497")
fb <- gsheet2tbl(url)
# browseURL(url)

# huito_fonts('Ceviche One')

label <- fb %>% 
  mutate(temp = paste0("Temperatura: ", temperatura)) %>% 
  mutate(var = paste0("Variedad: ", variedad)) %>% 
  label_layout(size = c(10, 2.5)
               , border_color = "blue"
               ) %>%
  include_image(
    value = "https://flavjack.github.io/inti/img/inkaverse.png"
    , size = c(2.4, 2.4)
    , position = c(1.2, 1.25)
    ) %>%
  include_barcode(
     value = "qr-code"
     , size = c(2.5, 2.5)
     , position = c(8.2, 1.25)
     ) %>%
  include_text(value = "plots"
               , position = c(9.7, 1.25)
               , angle = 90
               , size = 15
               , color = "red"
               ) %>%
  include_text(value = "Inkaverse"
               , position = c(4.6, 2)
               , size = 30
               , color = "brown"
               , font = 'Ceviche One'
               ) %>%
  include_text(value = "temp"
               , position = c(4.6, 1.2)
               , size = 13
               , color = "orange"
               ) %>%
  include_text(value = "var"
               , position = c(4.6, 0.5)
               , size = 13
               , color = "#009966"
               ) %>%
  label_print(mode = "s", smpres = 300, viewer = T)

```

After running the chunk the first time. You should change `fonts = F` as we already imported the fonts. If you want print the complete labels change: `mode = "complete"`.


```{r eval=FALSE, include=FALSE}
source("https://inkaverse.com/setup.r")

url <- "https://docs.google.com/spreadsheets/d/1rhIK4kqgp3UZFOAUGuSKQ45W7MpY98IxpQZSRb67LUY/edit#gid=334632135"
gs <- as_sheets_id(url)
# browseURL(url)

fb <- gs %>% 
  range_read("fb") %>% 
  select(1:tratamientos) %>% 
  mutate(bloque = paste("bloque:\n", block)) %>% 
  mutate(treat = paste("Tratamiento:\n", tratamientos)) 

# huito_fonts()

label <- fb %>% 
  label_layout(size = c(10, 2.5)
               , border_color = "red"
               ) %>% 
  include_barcode(value = "barcode"
                  , size = c(2.5, 2.5)
                  , position = c(8.2, 1.25)
                  ) %>%
  include_text(value = "plots"
               , position = c(9.7, 1.25)
               , angle = 90
               , size = 14
               , color = "red"
               ) %>%
  include_text(value = "plots"
               , position = c(0.5, 1.25)
               , angle = 90
               , size = 14
               , color = "red"
               ) %>%
  include_image(
    value = "https://upload.wikimedia.org/wikipedia/commons/a/a9/Unalm_logo.png"
    , size = c(1.8, 1.8)
    , position = c(2.2, 1.4)
  ) %>%
  include_text(value = "treat"
               , position = c(5, 1.9)
               , size = 12
               , color = "blue"
               ) %>%
  include_text(value = "bloque"
               , position = c(5, 0.9)
               , size = 12
               ) %>%
  include_text(value = "HECTOR FRANCISCO MELGAR CHIA"
               , position = c(3.7, 0.25)
               , size = 8
               , color = "#339966"
               ) %>%
  label_print(mode = "c"
              , viewer = F)
```

